# Generated by Django 4.2.3 on 2023-07-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('credor', models.BooleanField()),
                ('responsavel_pagamento', models.BooleanField()),
                ('responsavel_conta', models.BooleanField()),
            ],
            options={
                'db_table': 'Ator',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, max_length=150, null=True)),
                ('parcelas', models.IntegerField(default=0)),
                ('valor_devido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='S', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('P', 'Parcial'), ('Q', 'Quitado')], default='A', max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo.categoria')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_credor', to='fluxo.ator')),
                ('responsavel_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_responsavel_conta', to='fluxo.ator')),
                ('responsavel_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_responsavel_pagamento', to='fluxo.ator')),
            ],
            options={
                'db_table': 'Lancamento',
            },
        ),
        migrations.AddField(
            model_name='ator',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_categoria', to='fluxo.categoria'),
        ),
    ]
