# Generated by Django 4.2.3 on 2023-08-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0002_ator_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ator',
            name='credor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ator',
            name='responsavel_conta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ator',
            name='responsavel_pagamento',
            field=models.BooleanField(default=False),
        ),
    ]
